PROJETO DE TÉCNICAS DE PROGRAMAÇÃO I - PYTHON - COPA DO MUNDIAL FIFA
ALUNA: DENISE MARIA DE ASSIS ARAUJO - Id: 1629014
GRUPO:

In [56]:
# ==========================================================
# IMPORTAÇÃO DAS BIBLIOTECAS
# ==========================================================

# pandas = biblioteca usada para manipular dados
import pandas as pd

In [57]:
# ==========================================================
# CARREGAR O DATASET
# ==========================================================

# leitura do arquivo csv
# se o arquivo estiver na mesma pasta do notebook basta usar o nome

df = pd.read_csv("fifa_world_cup.csv")

# visualizar as primeiras linhas para entender a estrutura
df.head(10)

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,1,0,4,14,0,0,65,80,163,361
5,DENMARK,TUNISIA,55%,33%,12%,0,0,22 NOV 2022,14 : 00,Group D,...,0,0,11,11,0,0,76,73,226,287
6,MEXICO,POLAND,54%,31%,15%,0,0,22 NOV 2022,17 : 00,Group C,...,0,0,8,15,0,0,61,70,193,290
7,FRANCE,AUSTRALIA,56%,35%,9%,4,1,22 NOV 2022,20 : 00,Group D,...,0,0,4,22,0,0,64,56,250,316
8,MOROCCO,CROATIA,32%,57%,12%,0,0,23 NOV 2022,11 : 00,Group F,...,0,0,7,8,0,0,87,58,391,217
9,GERMANY,JAPAN,65%,22%,13%,1,2,23 NOV 2022,14 : 00,Group E,...,1,0,12,26,0,0,55,87,164,487

In [58]:
# shape mostra o tamanho da base de dados
# primeiro número = quantidade de linhas
# segundo número = quantidade de colunas
df.shape

(64, 88)

In [59]:
# lista todas as colunas do dataset
# isso ajuda a entender quais variáveis estão disponíveis para análise

df.columns

Index(['team1', 'team2', 'possession team1', 'possession team2',
       'possession in contest', 'number of goals team1',
       'number of goals team2', 'date', 'hour', 'category',
       'total attempts team1', 'total attempts team2', 'conceded team1',
       'conceded team2', 'goal inside the penalty area team1',
       'goal inside the penalty area team2',
       'goal outside the penalty area team1',
       'goal outside the penalty area team2', 'assists team1', 'assists team2',
       'on target attempts team1', 'on target attempts team2',
       'off target attempts team1', 'off target attempts team2',
       'attempts inside the penalty area team1',
       'attempts inside the penalty area  team2',
       'attempts outside the penalty area  team1',
       'attempts outside the penalty area  team2', 'left channel team1',
       'left channel team2', 'left inside channel team1',
       'left inside channel team2', 'central channel team1',
       'central channel team2', 'right inside channel team1',
       'right inside channel team2', 'right channel team1',
       'right channel team2', 'total offers to receive team1',
       'total offers to receive team2', 'inbehind offers to receive team1',
       'inbehind offers to receive team2', 'inbetween offers to receive team1',
       'inbetween offers to receive team2', 'infront offers to receive team1',
       'infront offers to receive team2',
       'receptions between midfield and defensive lines team1',
       'receptions between midfield and defensive lines team2',
       'attempted line breaks team1', 'attempted line breaks team2',
       'completed line breaksteam1', 'completed line breaks team2',
       'attempted defensive line breaks team1',
       'attempted defensive line breaks team2',
       'completed defensive line breaksteam1',
       'completed defensive line breaks team2', 'yellow cards team1',
       'yellow cards team2', 'red cards team1', 'red cards team2',
       'fouls against team1', 'fouls against team2', 'offsides team1',
       'offsides team2', 'passes team1', 'passes team2',
       'passes completed team1', 'passes completed team2', 'crosses team1',
       'crosses team2', 'crosses completed team1', 'crosses completed team2',
       'switches of play completed team1', 'switches of play completed team2',
       'corners team1', 'corners team2', 'free kicks team1',
       'free kicks team2', 'penalties scored team1', 'penalties scored team2',
       'goal preventions team1', 'goal preventions team2', 'own goals team1',
       'own goals team2', 'forced turnovers team1', 'forced turnovers team2',
       'defensive pressures applied team1',
       'defensive pressures applied team2'],
      dtype='object')

In [60]:
# aqui eu verifico o tipo de cada coluna
# isso é importante para saber se os dados são números ou texto

df.dtypes

team1                                object
team2                                object
possession team1                     object
possession team2                     object
possession in contest                object
                                      ...
own goals team2                       int64
forced turnovers team1                int64
forced turnovers team2                int64
defensive pressures applied team1     int64
defensive pressures applied team2     int64
Length: 88, dtype: object

In [23]:
# o info mostra um resumo geral da tabela
# aqui dá para ver quantidade de valores e se existem dados faltando

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 88 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   team1                                                  64 non-null     object
 1   team2                                                  64 non-null     object
 2   possession team1                                       64 non-null     object
 3   possession team2                                       64 non-null     object
 4   possession in contest                                  64 non-null     object
 5   number of goals team1                                  64 non-null     int64
 6   number of goals team2                                  64 non-null     int64
 7   date                                                   64 non-null     object
 8   hour                                                   64 non-null     object
 9   category                                               64 non-null     object
 10  total attempts team1                                   64 non-null     int64
 11  total attempts team2                                   64 non-null     int64
 12  conceded team1                                         64 non-null     int64
 13  conceded team2                                         64 non-null     int64
 14  goal inside the penalty area team1                     64 non-null     int64
 15  goal inside the penalty area team2                     64 non-null     int64
 16  goal outside the penalty area team1                    64 non-null     int64
 17  goal outside the penalty area team2                    64 non-null     int64
 18  assists team1                                          64 non-null     int64
 19  assists team2                                          64 non-null     int64
 20  on target attempts team1                               64 non-null     int64
 21  on target attempts team2                               64 non-null     int64
 22  off target attempts team1                              64 non-null     int64
 23  off target attempts team2                              64 non-null     int64
 24  attempts inside the penalty area team1                 64 non-null     int64
 25  attempts inside the penalty area  team2                64 non-null     int64
 26  attempts outside the penalty area  team1               64 non-null     int64
 27  attempts outside the penalty area  team2               64 non-null     int64
 28  left channel team1                                     64 non-null     int64
 29  left channel team2                                     64 non-null     int64
 30  left inside channel team1                              64 non-null     int64
 31  left inside channel team2                              64 non-null     int64
 32  central channel team1                                  64 non-null     int64
 33  central channel team2                                  64 non-null     int64
 34  right inside channel team1                             64 non-null     int64
 35  right inside channel team2                             64 non-null     int64
 36  right channel team1                                    64 non-null     int64
 37  right channel team2                                    64 non-null     int64
 38  total offers to receive team1                          64 non-null     int64
 39  total offers to receive team2                          64 non-null     int64
 40  inbehind offers to receive team1                       64 non-null     int64
 41  inbehind offers to receive team2                       64 non-null     int64
 42  inbetween offers to receive team1                      64 non-null     int64
 43  inbetween offers to receive team2                      64 non-null     int64
 44  infront offers to receive team1                        64 non-null     int64
 45  infront offers to receive team2                        64 non-null     int64
 46  receptions between midfield and defensive lines team1  64 non-null     int64
 47  receptions between midfield and defensive lines team2  64 non-null     int64
 48  attempted line breaks team1                            64 non-null     int64
 49  attempted line breaks team2                            64 non-null     int64
 50  completed line breaksteam1                             64 non-null     int64
 51  completed line breaks team2                            64 non-null     int64
 52  attempted defensive line breaks team1                  64 non-null     int64
 53  attempted defensive line breaks team2                  64 non-null     int64
 54  completed defensive line breaksteam1                   64 non-null     int64
 55  completed defensive line breaks team2                  64 non-null     int64
 56  yellow cards team1                                     64 non-null     int64
 57  yellow cards team2                                     64 non-null     int64
 58  red cards team1                                        64 non-null     int64
 59  red cards team2                                        64 non-null     int64
 60  fouls against team1                                    64 non-null     int64
 61  fouls against team2                                    64 non-null     int64
 62  offsides team1                                         64 non-null     int64
 63  offsides team2                                         64 non-null     int64
 64  passes team1                                           64 non-null     int64
 65  passes team2                                           64 non-null     int64
 66  passes completed team1                                 64 non-null     int64
 67  passes completed team2                                 64 non-null     int64
 68  crosses team1                                          64 non-null     int64
 69  crosses team2                                          64 non-null     int64
 70  crosses completed team1                                64 non-null     int64
 71  crosses completed team2                                64 non-null     int64
 72  switches of play completed team1                       64 non-null     int64
 73  switches of play completed team2                       64 non-null     int64
 74  corners team1                                          64 non-null     int64
 75  corners team2                                          64 non-null     int64
 76  free kicks team1                                       64 non-null     int64
 77  free kicks team2                                       64 non-null     int64
 78  penalties scored team1                                 64 non-null     int64
 79  penalties scored team2                                 64 non-null     int64
 80  goal preventions team1                                 64 non-null     int64
 81  goal preventions team2                                 64 non-null     int64
 82  own goals team1                                        64 non-null     int64
 83  own goals team2                                        64 non-null     int64
 84  forced turnovers team1                                 64 non-null     int64
 85  forced turnovers team2                                 64 non-null     int64
 86  defensive pressures applied team1                      64 non-null     int64
 87  defensive pressures applied team2                      64 non-null     int64
dtypes: int64(80), object(8)
memory usage: 44.1+ KB

In [61]:
# calcula estatísticas das colunas numéricas
# inclui média, mínimo, máximo e desvio padrão

df.describe()

,number of goals team1,number of goals team2,total attempts team1,total attempts team2,conceded team1,conceded team2,goal inside the penalty area team1,goal inside the penalty area team2,goal outside the penalty area team1,goal outside the penalty area team2,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
count,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,...,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000
mean,1.578125,1.109375,11.140625,11.281250,1.109375,1.578125,1.468750,0.984375,0.093750,0.109375,...,0.140625,0.125000,11.593750,11.359375,0.015625,0.015625,71.968750,70.125000,289.750000,293.265625
std,1.551289,1.055856,4.972519,5.807682,1.055856,1.551289,1.563155,0.999876,0.293785,0.314576,...,0.350382,0.377964,5.911299,4.990045,0.125000,0.125000,14.394629,13.531269,88.406888,80.916230
min,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,38.000000,44.000000,139.000000,141.000000
25%,0.000000,0.000000,8.000000,7.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,7.750000,8.000000,0.000000,0.000000,63.000000,60.250000,229.000000,233.750000
50%,1.000000,1.000000,10.000000,10.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,11.000000,10.000000,0.000000,0.000000,71.000000,72.000000,281.000000,292.500000
75%,2.000000,2.000000,14.000000,14.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,14.000000,14.000000,0.000000,0.000000,83.500000,79.000000,328.000000,327.500000
max,7.000000,4.000000,25.000000,32.000000,4.000000,7.000000,7.000000,4.000000,1.000000,1.000000,...,1.000000,2.000000,32.000000,26.000000,1.000000,1.000000,101.000000,104.000000,637.000000,585.000000

In [62]:
# aqui estou verificando se existem dados faltando
# o isnull identifica valores vazios
# o sum conta quantos existem em cada coluna

df.isnull().sum()

team1                                0
team2                                0
possession team1                     0
possession team2                     0
possession in contest                0
                                    ..
own goals team2                      0
forced turnovers team1               0
forced turnovers team2               0
defensive pressures applied team1    0
defensive pressures applied team2    0
Length: 88, dtype: int64

In [63]:
# ==========================================================
# VERIFICAR VALORES DISTINTOS
# ==========================================================

# quantos valores diferentes existem em algumas colunas
df.nunique().head(10)

team1                    32
team2                    32
possession team1         32
possession team2         34
possession in contest    11
number of goals team1     7
number of goals team2     5
date                     23
hour                      5
category                 13
dtype: int64

In [65]:
# ==========================================================
# TRATAMENTO DE DADOS
# ==========================================================

# remover linhas com valores nulos
df = df.dropna()

# remover linhas duplicadas
df = df.drop_duplicates()

# verificar novamente se existem nulos
df.isnull().sum().head(10)

team1                    0
team2                    0
possession team1         0
possession team2         0
possession in contest    0
number of goals team1    0
number of goals team2    0
date                     0
hour                     0
category                 0
dtype: int64

In [66]:
# aqui eu removo colunas que possuem apenas um único valor
# colunas assim não ajudam na análise

df = df.loc[:, df.nunique() > 1]

In [67]:
# aqui estou criando uma nova coluna
# ela representa o total de gols da partida

df['total_goals'] = df['number of goals team1'] + df['number of goals team2']

In [ ]:
# ==========================================================
# PERGUNTA 1
# Quais os times marcaram mais gols? (cite os 10 primeiros)
# ==========================================================
df.groupby('team1')['number of goals team1'].sum().sort_values(ascending=False).head(10)

team1
ARGENTINA         11
PORTUGAL          11
FRANCE            11
ENGLAND           10
SPAIN              8
NETHERLANDS        8
BRAZIL             7
CROATIA            7
KOREA REPUBLIC     4
CAMEROON           4
Name: number of goals team1, dtype: int64

In [73]:
# ==========================================================
# PERGUNTA 2
# Qual o jogo teve mais gols?
# ==========================================================
# ordeno os jogos pelo total de gols
# head(1) mostra apenas o jogo com maior valor

df.sort_values('total_goals', ascending=False).head(1)

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2,total_goals
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,1,8,13,0,0,63,72,139,416,8

In [81]:
# ==========================================================
# PERGUNTA 3:
# Quais os times tiveram a MAIOR POSSE DE BOLA MÉDIA (cite os 10 primeiros)?
# ==========================================================

# primeiro vou garantir que a coluna esteja em formato texto
# isso evita erro caso alguns valores sejam números
df['possession team1'] = df['possession team1'].astype(str)

# agora removo o símbolo %
# regex=False evita problemas de interpretação
df['possession team1'] = df['possession team1'].str.replace('%', '', regex=False)

# converto novamente para número
# errors='coerce' transforma valores problemáticos em NaN
df['possession team1'] = pd.to_numeric(df['possession team1'], errors='coerce')

# agora sim posso calcular a média de posse por time
posse_media = (
    df.groupby('team1')['possession team1']
    .mean()
    .sort_values(ascending=False)
)

# mostrar resultado
posse_media.head(10)

team1
SPAIN            65.000000
GERMANY          65.000000
ENGLAND          57.750000
DENMARK          55.000000
MEXICO           54.000000
CANADA           52.000000
ECUADOR          51.000000
UNITED STATES    51.000000
BELGIUM          51.000000
BRAZIL           50.333333
Name: possession team1, dtype: float64

In [ ]:
# ==========================================================
# PERGUNTA 4:
# Quais os times deram mais CHUTES A GOL (cite os 10 primeiros)?
# ==========================================================

df.groupby('team1')['on target attempts team1'].sum().sort_values(ascending=False).head(10)

team1
ARGENTINA         29
BRAZIL            24
FRANCE            22
ENGLAND           20
CROATIA           19
PORTUGAL          18
NETHERLANDS       13
KOREA REPUBLIC    12
CAMEROON          11
SPAIN             10
Name: on target attempts team1, dtype: int64

In [ ]:
# ==========================================================
# PERGUNTA 5:
# Quais os times deram mais PASSES (cite os 10 primeiros)?
# ==========================================================
#  #soma total de passes realizados por cada time

df.groupby('team1')['passes team1'].sum().sort_values(ascending=False).head(10)

team1
ARGENTINA      2910
ENGLAND        2464
NETHERLANDS    2366
CROATIA        2246
FRANCE         2135
BRAZIL         1766
SPAIN          1708
PORTUGAL       1693
JAPAN          1332
BELGIUM        1183
Name: passes team1, dtype: int64

In [ ]:
# ==========================================================
# PERGUNTA 6:
# Quais os jogos tiveram mais CARTÕES AMARELOS (cite os 10 primeiros)?
# ==========================================================
# primeiro crio uma coluna com o total de cartões da partida

df['total_yellow'] = df['yellow cards team1'] + df['yellow cards team2']

# depois ordeno para encontrar o jogo com mais cartões

df.sort_values('total_yellow', ascending=False).head(10)

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2,total_goals,total_yellow
57,NETHERLANDS,ARGENTINA,45,44%,11%,2,2,09 DEC 2022,20 : 00,Quarter-final,...,15,5,0,0,91,79,401,323,4,16
46,SERBIA,SWITZERLAND,45,41%,14%,2,3,02 DEC 2022,20 : 00,Group G,...,14,10,0,0,74,82,276,253,5,11
63,ARGENTINA,FRANCE,46,40%,14%,3,3,18 DEC 2022,16 : 00,Final,...,11,21,0,0,87,104,280,409,6,7
47,CAMEROON,BRAZIL,31,56%,13%,1,0,02 DEC 2022,20 : 00,Group G,...,20,7,0,0,78,54,321,226,1,7
44,GHANA,URUGUAY,46,39%,15%,0,2,02 DEC 2022,16 : 00,Group H,...,12,9,0,0,92,84,248,293,2,7
39,SAUDI ARABIA,MEXICO,29,55%,17%,1,2,30 NOV 2022,20 : 00,Group C,...,26,10,0,0,82,76,269,229,3,7
14,PORTUGAL,GHANA,55,35%,10%,3,2,24 NOV 2022,17 : 00,Group H,...,8,11,0,0,70,82,286,326,5,6
24,JAPAN,COSTA RICA,48,39%,13%,0,1,27 NOV 2022,11 : 00,Group E,...,4,14,0,0,47,66,300,294,1,6
17,QATAR,SENEGAL,42,48%,10%,1,3,25 NOV 2022,14 : 00,Group A,...,12,11,0,0,67,67,308,232,4,6
0,QATAR,ECUADOR,42,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,6,5,0,0,52,72,256,279,2,6

In [85]:
# ==========================================================
# PERGUNTA 7:
# Quais os times sofreram mais FALTAS (cite os 10 primeiros)?
# ==========================================================
# soma total de faltas sofridas por cada time

df.groupby('team1')['fouls against team1'].sum().sort_values(ascending=False).head(10)

team1
NETHERLANDS    74
ARGENTINA      71
CROATIA        55
MOROCCO        47
ENGLAND        44
JAPAN          44
PORTUGAL       36
TUNISIA        30
FRANCE         30
WALES          25
Name: fouls against team1, dtype: int64

In [89]:
# ==========================================================
# PERGUNTA 8:
# Quais os times tiveram mais ESCANTEIOS (cite os 10 primeiros)?
# ==========================================================
# soma total de escanteios por time

df.groupby('team1')['corners team1'].sum().sort_values(ascending=False).head(10)

team1
FRANCE            23
ARGENTINA         22
ENGLAND           19
BRAZIL            19
KOREA REPUBLIC    17
CROATIA           16
PORTUGAL          15
BELGIUM           13
JAPAN             13
NETHERLANDS       12
Name: corners team1, dtype: int64

In [90]:
# ==========================================================
# PERGUNTA 9:
# Quais os times tiveram mais IMPEDIMENTOS (cite os 10 primeiros)?
# ==========================================================
# soma total de impedimentos por time

df.groupby('team1')['offsides team1'].sum().sort_values(ascending=False).head(10)

team1
ARGENTINA      21
CROATIA        10
FRANCE          8
QATAR           7
MOROCCO         7
TUNISIA         6
PORTUGAL        6
NETHERLANDS     6
SPAIN           5
JAPAN           5
Name: offsides team1, dtype: int64

In [94]:
# ==========================================================
# PERGUNTA 10:
# Quais os times apresentaram maior PRESSÃO DEFENSIVA (cite os 10 primeiros)?
# ==========================================================

# soma total de pressões defensivas aplicadas por time

df.groupby('team1')['defensive pressures applied team1'].sum().sort_values(ascending=False).head(10)

team1
JAPAN          1342
MOROCCO        1337
CROATIA        1328
NETHERLANDS    1299
ARGENTINA      1224
FRANCE         1067
PORTUGAL        869
BRAZIL          828
ENGLAND         828
POLAND          767
Name: defensive pressures applied team1, dtype: int64