GRUPO: 
Denise Maria de Assis Araújo - git: denisea7@gmail.com
Itamar Vieira Maciel - git: itamarvmback@gmail.com
Sérgio Pereira Domingos - git: domin.sergio@gmail.com

Curso: CAIXAVERSO - FC | Analista Dados - I | #1629

Módulo: Técnicas de Programação (PY) Professor: Rogério Mainardes

Projeto: Análise de Dados – Partidas da Copa do Mundo

In [1]:
# ==========================================================
# IMPORTAÇÃO DAS BIBLIOTECAS
# ==========================================================    

# pandas = biblioteca usada para manipular dados
import pandas as pd

In [2]:
# ==========================================================
# CARREGAR O DATASET
# ==========================================================

# leitura do arquivo csv
# se o arquivo estiver na mesma pasta do notebook basta usar o nome

df = pd.read_csv("fifa_world_cup.csv")

# visualizar as primeiras linhas para entender a estrutura
df.head(10)

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,free kicks team1,free kicks team2,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,19,17,0,1,6,5,0,0,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,16,10,0,1,8,13,0,0,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,14,14,0,0,9,15,0,0,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,11,15,0,1,7,7,0,0,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,22,16,1,0,4,14,0,0,163,361
5,DENMARK,TUNISIA,55%,33%,12%,0,0,22 NOV 2022,14 : 00,Group D,...,11,10,0,0,11,11,0,0,226,287
6,MEXICO,POLAND,54%,31%,15%,0,0,22 NOV 2022,17 : 00,Group C,...,16,16,0,0,8,15,0,0,193,290
7,FRANCE,AUSTRALIA,56%,35%,9%,4,1,22 NOV 2022,20 : 00,Group D,...,11,5,0,0,4,22,0,0,250,316
8,MOROCCO,CROATIA,32%,57%,12%,0,0,23 NOV 2022,11 : 00,Group F,...,12,17,0,0,7,8,0,0,391,217
9,GERMANY,JAPAN,65%,22%,13%,1,2,23 NOV 2022,14 : 00,Group E,...,17,10,1,0,12,26,0,0,164,487

In [3]:
# shape mostra o tamanho da base de dados
# primeiro número = quantidade de linhas
# segundo número = quantidade de colunas
df.shape

(64, 56)

In [4]:
# lista todas as colunas do dataset
# isso ajuda a entender quais variáveis estão disponíveis para análise

df.columns

Index(['team1', 'team2', 'possession team1', 'possession team2',
       'possession in contest', 'number of goals team1',
       'number of goals team2', 'date', 'hour', 'category',
       'total attempts team1', 'total attempts team2',
       'goal inside the penalty area team1',
       'goal inside the penalty area team2',
       'goal outside the penalty area team1',
       'goal outside the penalty area team2', 'assists team1', 'assists team2',
       'on target attempts team1', 'on target attempts team2',
       'off target attempts team1', 'off target attempts team2',
       'attempts inside the penalty area team1',
       'attempts inside the penalty area  team2',
       'attempts outside the penalty area  team1',
       'attempts outside the penalty area  team2', 'yellow cards team1',
       'yellow cards team2', 'red cards team1', 'red cards team2',
       'fouls against team1', 'fouls against team2', 'offsides team1',
       'offsides team2', 'passes team1', 'passes team2',
       'passes completed team1', 'passes completed team2', 'crosses team1',
       'crosses team2', 'crosses completed team1', 'crosses completed team2',
       'switches of play completed team1', 'switches of play completed team2',
       'corners team1', 'corners team2', 'free kicks team1',
       'free kicks team2', 'penalties scored team1', 'penalties scored team2',
       'goal preventions team1', 'goal preventions team2', 'own goals team1',
       'own goals team2', 'defensive pressures applied team1',
       'defensive pressures applied team2'],
      dtype='str')

In [5]:
# aqui eu verifico o tipo de cada coluna
# isso é importante para saber se os dados são números ou texto

df.dtypes

team1                                         str
team2                                         str
possession team1                              str
possession team2                              str
possession in contest                         str
number of goals team1                       int64
number of goals team2                       int64
date                                          str
hour                                          str
category                                      str
total attempts team1                        int64
total attempts team2                        int64
goal inside the penalty area team1          int64
goal inside the penalty area team2          int64
goal outside the penalty area team1         int64
goal outside the penalty area team2         int64
assists team1                               int64
assists team2                               int64
on target attempts team1                    int64
on target attempts team2                    int64
off target attempts team1                   int64
off target attempts team2                   int64
attempts inside the penalty area team1      int64
attempts inside the penalty area  team2     int64
attempts outside the penalty area  team1    int64
attempts outside the penalty area  team2    int64
yellow cards team1                          int64
yellow cards team2                          int64
red cards team1                             int64
red cards team2                             int64
fouls against team1                         int64
fouls against team2                         int64
offsides team1                              int64
offsides team2                              int64
passes team1                                int64
passes team2                                int64
passes completed team1                      int64
passes completed team2                      int64
crosses team1                               int64
crosses team2                               int64
crosses completed team1                     int64
crosses completed team2                     int64
switches of play completed team1            int64
switches of play completed team2            int64
corners team1                               int64
corners team2                               int64
free kicks team1                            int64
free kicks team2                            int64
penalties scored team1                      int64
penalties scored team2                      int64
goal preventions team1                      int64
goal preventions team2                      int64
own goals team1                             int64
own goals team2                             int64
defensive pressures applied team1           int64
defensive pressures applied team2           int64
dtype: object

In [6]:
# o info mostra um resumo geral da tabela
# aqui dá para ver quantidade de valores e se existem dados faltando

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 56 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   team1                                     64 non-null     str
 1   team2                                     64 non-null     str
 2   possession team1                          64 non-null     str
 3   possession team2                          64 non-null     str
 4   possession in contest                     64 non-null     str
 5   number of goals team1                     64 non-null     int64
 6   number of goals team2                     64 non-null     int64
 7   date                                      64 non-null     str
 8   hour                                      64 non-null     str
 9   category                                  64 non-null     str
 10  total attempts team1                      64 non-null     int64
 11  total attempts team2                      64 non-null     int64
 12  goal inside the penalty area team1        64 non-null     int64
 13  goal inside the penalty area team2        64 non-null     int64
 14  goal outside the penalty area team1       64 non-null     int64
 15  goal outside the penalty area team2       64 non-null     int64
 16  assists team1                             64 non-null     int64
 17  assists team2                             64 non-null     int64
 18  on target attempts team1                  64 non-null     int64
 19  on target attempts team2                  64 non-null     int64
 20  off target attempts team1                 64 non-null     int64
 21  off target attempts team2                 64 non-null     int64
 22  attempts inside the penalty area team1    64 non-null     int64
 23  attempts inside the penalty area  team2   64 non-null     int64
 24  attempts outside the penalty area  team1  64 non-null     int64
 25  attempts outside the penalty area  team2  64 non-null     int64
 26  yellow cards team1                        64 non-null     int64
 27  yellow cards team2                        64 non-null     int64
 28  red cards team1                           64 non-null     int64
 29  red cards team2                           64 non-null     int64
 30  fouls against team1                       64 non-null     int64
 31  fouls against team2                       64 non-null     int64
 32  offsides team1                            64 non-null     int64
 33  offsides team2                            64 non-null     int64
 34  passes team1                              64 non-null     int64
 35  passes team2                              64 non-null     int64
 36  passes completed team1                    64 non-null     int64
 37  passes completed team2                    64 non-null     int64
 38  crosses team1                             64 non-null     int64
 39  crosses team2                             64 non-null     int64
 40  crosses completed team1                   64 non-null     int64
 41  crosses completed team2                   64 non-null     int64
 42  switches of play completed team1          64 non-null     int64
 43  switches of play completed team2          64 non-null     int64
 44  corners team1                             64 non-null     int64
 45  corners team2                             64 non-null     int64
 46  free kicks team1                          64 non-null     int64
 47  free kicks team2                          64 non-null     int64
 48  penalties scored team1                    64 non-null     int64
 49  penalties scored team2                    64 non-null     int64
 50  goal preventions team1                    64 non-null     int64
 51  goal preventions team2                    64 non-null     int64
 52  own goals team1                           64 non-null     int64
 53  own goals team2                           64 non-null     int64
 54  defensive pressures applied team1         64 non-null     int64
 55  defensive pressures applied team2         64 non-null     int64
dtypes: int64(48), str(8)
memory usage: 28.1 KB

In [7]:
# calcula estatísticas das colunas numéricas
# inclui média, mínimo, máximo e desvio padrão

df.describe()

,number of goals team1,number of goals team2,total attempts team1,total attempts team2,goal inside the penalty area team1,goal inside the penalty area team2,goal outside the penalty area team1,goal outside the penalty area team2,assists team1,assists team2,...,free kicks team1,free kicks team2,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,defensive pressures applied team1,defensive pressures applied team2
count,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,...,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000
mean,1.578125,1.109375,11.140625,11.281250,1.468750,0.984375,0.093750,0.109375,1.171875,0.734375,...,14.093750,14.390625,0.140625,0.125000,11.593750,11.359375,0.015625,0.015625,289.750000,293.265625
std,1.551289,1.055856,4.972519,5.807682,1.563155,0.999876,0.293785,0.314576,1.363407,0.895176,...,4.219075,5.202616,0.350382,0.377964,5.911299,4.990045,0.125000,0.125000,88.406888,80.916230
min,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.000000,5.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,139.000000,141.000000
25%,0.000000,0.000000,8.000000,7.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,11.000000,11.000000,0.000000,0.000000,7.750000,8.000000,0.000000,0.000000,229.000000,233.750000
50%,1.000000,1.000000,10.000000,10.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,14.000000,14.500000,0.000000,0.000000,11.000000,10.000000,0.000000,0.000000,281.000000,292.500000
75%,2.000000,2.000000,14.000000,14.000000,2.000000,2.000000,0.000000,0.000000,2.000000,1.000000,...,16.000000,17.000000,0.000000,0.000000,14.000000,14.000000,0.000000,0.000000,328.000000,327.500000
max,7.000000,4.000000,25.000000,32.000000,7.000000,4.000000,1.000000,1.000000,6.000000,4.000000,...,27.000000,30.000000,1.000000,2.000000,32.000000,26.000000,1.000000,1.000000,637.000000,585.000000

In [8]:
# aqui estou verificando se existem dados faltando
# o isnull identifica valores vazios
# o sum conta quantos existem em cada coluna

df.isnull().sum()

team1                                       0
team2                                       0
possession team1                            0
possession team2                            0
possession in contest                       0
number of goals team1                       0
number of goals team2                       0
date                                        0
hour                                        0
category                                    0
total attempts team1                        0
total attempts team2                        0
goal inside the penalty area team1          0
goal inside the penalty area team2          0
goal outside the penalty area team1         0
goal outside the penalty area team2         0
assists team1                               0
assists team2                               0
on target attempts team1                    0
on target attempts team2                    0
off target attempts team1                   0
off target attempts team2                   0
attempts inside the penalty area team1      0
attempts inside the penalty area  team2     0
attempts outside the penalty area  team1    0
attempts outside the penalty area  team2    0
yellow cards team1                          0
yellow cards team2                          0
red cards team1                             0
red cards team2                             0
fouls against team1                         0
fouls against team2                         0
offsides team1                              0
offsides team2                              0
passes team1                                0
passes team2                                0
passes completed team1                      0
passes completed team2                      0
crosses team1                               0
crosses team2                               0
crosses completed team1                     0
crosses completed team2                     0
switches of play completed team1            0
switches of play completed team2            0
corners team1                               0
corners team2                               0
free kicks team1                            0
free kicks team2                            0
penalties scored team1                      0
penalties scored team2                      0
goal preventions team1                      0
goal preventions team2                      0
own goals team1                             0
own goals team2                             0
defensive pressures applied team1           0
defensive pressures applied team2           0
dtype: int64

In [9]:
# ==========================================================
# VERIFICAR VALORES DISTINTOS
# ==========================================================

# quantos valores diferentes existem em algumas colunas
df.nunique().head(10)

team1                    32
team2                    32
possession team1         32
possession team2         34
possession in contest    11
number of goals team1     7
number of goals team2     5
date                     23
hour                      5
category                 13
dtype: int64

In [10]:
# ==========================================================
# TRATAMENTO DE DADOS
# ==========================================================

# remover linhas com valores nulos
df = df.dropna()

# remover linhas duplicadas
df = df.drop_duplicates()

# verificar novamente se existem nulos
df.isnull().sum().head(10)

team1                    0
team2                    0
possession team1         0
possession team2         0
possession in contest    0
number of goals team1    0
number of goals team2    0
date                     0
hour                     0
category                 0
dtype: int64

In [11]:
# aqui eu removo colunas que possuem apenas um único valor
# colunas assim não ajudam na análise

df = df.loc[:, df.nunique() > 1]

In [18]:
# aqui estou criando uma nova coluna
# ela representa o total de gols da partida

df['total_goals'] = df['number of goals team1'] + df['number of goals team2']

In [12]:
# ==========================================================
# PERGUNTA 1:
# Quais os times marcaram mais gols (melhores ataques)? (cite os 10 primeiros)
# ==========================================================

# Somar gols quando o time aparece como team1
gols_team1 = df.groupby('team1')['number of goals team1'].sum()

# Somar gols quando o time aparece como team2
gols_team2 = df.groupby('team2')['number of goals team2'].sum()

# Somar os dois resultados
total_gols = gols_team1.add(gols_team2, fill_value=0)

resultado = total_gols.sort_values(ascending=False).head(10).reset_index()
resultado.columns = ['Time', 'Total de Gols']

display(resultado)

          Time  Total de Gols
0       FRANCE             16
1    ARGENTINA             15
2      ENGLAND             13
3     PORTUGAL             12
4  NETHERLANDS             10
5        SPAIN              9
6      CROATIA              8
7       BRAZIL              8
8      MOROCCO              6
9      GERMANY              6

In [29]:
# ==========================================================
# PERGUNTA 2:
# Quais os times marcaram sofreram mais gols (defesas mais vazadas)? (cite os 10 primeiros)
# ==========================================================

# Somar gols que o team1 tomou, somando o gols do outro lado (team2)
gols_team1 = df.groupby('team1')['number of goals team2'].sum()

# Somar gols que o team2 tomou, somando o gols do outro lado (team1)
gols_team2 = df.groupby('team2')['number of goals team1'].sum()

# Somar os dois resultados
total_gols = gols_team1.add(gols_team2, fill_value=0)

resultado = total_gols.sort_values(ascending=False).head(10).reset_index()
resultado.columns = ['Time', 'Total de Gols']

display(resultado)

             Time  Total de Gols
0      COSTA RICA             11
1     SWITZERLAND              9
2          FRANCE              8
3       ARGENTINA              8
4  KOREA REPUBLIC              8
5          SERBIA              8
6           GHANA              7
7          CANADA              7
8           QATAR              7
9            IRAN              7

In [13]:
# ==========================================================
# PERGUNTA 3:
# Qual os jogos tiveram mais gols (cite os 10 primeiros)?
# ==========================================================

# cria uma coluna com o total de gols da partida
df['total_gols'] = df['number of goals team1'] + df['number of goals team2']

# ordena os jogos pelo total de gols (do maior para o menor)
top10_jogos_gols = df.sort_values(by='total_gols', ascending=False)

# mostra os 10 jogos com mais gols
resultado = top10_jogos_gols[['team1', 'team2', 'number of goals team1', 'number of goals team2', 'total_gols']].head(10)

display(resultado)

,team1,team2,number of goals team1,number of goals team2,total_gols
1,ENGLAND,IRAN,6,2,8
10,SPAIN,COSTA RICA,7,0,7
55,PORTUGAL,SWITZERLAND,6,1,7
28,CAMEROON,SERBIA,3,3,6
43,COSTA RICA,GERMANY,2,4,6
63,ARGENTINA,FRANCE,3,3,6
26,CROATIA,CANADA,4,1,5
14,PORTUGAL,GHANA,3,2,5
46,SERBIA,SWITZERLAND,2,3,5
29,KOREA REPUBLIC,GHANA,2,3,5

In [33]:
# ==========================================================
# PERGUNTA 4: Qual jogo teve a maior diferença de gols (maior goleada)?
# ==========================================================

# Calcular a diferença de gols usando valor absoluto (função "abs" = |módulo| )
df['goal_difference'] = abs(df['number of goals team1'] - df['number of goals team2'])

# Encontrar o jogo com a maior diferença de gols (maior goleada)
max_diff_game = df.loc[df['goal_difference'].idxmax()]

# Mostrar o resultado
print("Jogo com maior diferença de gols:")
print(f"{max_diff_game['team1']} {max_diff_game['number of goals team1']} x {max_diff_game['number of goals team2']} {max_diff_game['team2']}")
print(f"Diferença: {max_diff_game['goal_difference']} gols")

Jogo com maior diferença de gols:
SPAIN 7 x 0 COSTA RICA
Diferença: 7 gols

In [14]:
# ==========================================================
# PERGUNTA 5:
# Quais os times tiveram a MAIOR POSSE DE BOLA MÉDIA (cite os 10 primeiros)?
# ==========================================================

# Função para calcular a posse média considerando ambos os times
def average_possession(df):
    # --- Preparar posse de team1 ---
    df['possession team1'] = df['possession team1'].astype(str).str.replace('%','', regex=False)
    df['possession team1'] = pd.to_numeric(df['possession team1'], errors='coerce')
    
    # --- Preparar posse de team2 ---
    df['possession team2'] = df['possession team2'].astype(str).str.replace('%','', regex=False)
    df['possession team2'] = pd.to_numeric(df['possession team2'], errors='coerce')
    
    # Média da posse de cada time
    posse1 = df.groupby('team1')['possession team1'].mean()
    posse2 = df.groupby('team2')['possession team2'].mean()
    
    # Combinar as médias (soma das duas quando o time aparece em team1 ou team2)
    posse_total = posse1.add(posse2, fill_value=0)
    
    # Transformar em DataFrame limpo
    posse_df = posse_total.reset_index()
    posse_df.columns = ['Time', 'Maior Posse de Bola Média']
    
    # Retornar os 10 maiores
    return posse_df.sort_values('Maior Posse de Bola Média', ascending=False).head(10)

# Usar a função
average_possession(df)

         Time  Maior Posse de Bola Média
26      SPAIN                 138.000000
10    ENGLAND                 115.750000
12    GERMANY                 111.500000
21   PORTUGAL                 110.333333
8     DENMARK                 107.000000
0   ARGENTINA                 104.900000
3      BRAZIL                 100.833333
17     MEXICO                  99.500000
2     BELGIUM                  98.000000
7     CROATIA                  97.500000

In [15]:
# ==========================================================
# PERGUNTA 6:
# Quais os times deram mais CHUTES A GOL (cite os 10 primeiros)?
# ==========================================================

def total_shots_on_target(df):
    # Somatório dos chutes quando o time é team1
    shots_team1 = df.groupby('team1')['on target attempts team1'].sum()
    # Somatório dos chutes quando o time é team2
    shots_team2 = df.groupby('team2')['on target attempts team2'].sum()
    # Somar os dois
    total_shots = shots_team1.add(shots_team2, fill_value=0)
    # Transformar em DataFrame limpo
    shots_df = total_shots.reset_index()
    shots_df.columns = ['Time', 'Total de Chutes a Gol']
    return shots_df

total_shots_on_target(df).sort_values('Total de Chutes a Gol', ascending=False).head(10)

              Time  Total de Chutes a Gol
0        ARGENTINA                     48
3           BRAZIL                     41
11          FRANCE                     35
7          CROATIA                     28
10         ENGLAND                     27
21        PORTUGAL                     25
12         GERMANY                     24
16  KOREA REPUBLIC                     18
18         MOROCCO                     17
19     NETHERLANDS                     16

In [16]:
# ==========================================================
# PERGUNTA 7:
# Quais os times deram mais PASSES (cite os 10 primeiros)?
# ==========================================================
#  #soma total de passes realizados por cada time

def total_passes(df):
    # Somar passes quando o time é team1
    passes_team1 = df.groupby('team1')['passes team1'].sum()
    # Somar passes quando o time é team2
    passes_team2 = df.groupby('team2')['passes team2'].sum()
    # Somar os dois
    total_passes = passes_team1.add(passes_team2, fill_value=0)
    # Transformar em DataFrame limpo
    passes_df = total_passes.reset_index()
    passes_df.columns = ['Time', 'Total Passes']
    return passes_df

total_passes(df).sort_values('Total Passes', ascending=False).head(10)

             Time  Total Passes
0       ARGENTINA          4375
7         CROATIA          4272
26          SPAIN          3819
11         FRANCE          3656
10        ENGLAND          3052
3          BRAZIL          3009
21       PORTUGAL          2977
19    NETHERLANDS          2804
18        MOROCCO          2690
29  UNITED STATES          2033

In [17]:
# PERGUNTA 8:
# Quais os jogos tiveram mais CARTÕES AMARELOS (cite os 10 primeiros)?
# ==========================================================

# criar coluna com total de cartões amarelos da partida
df['total_yellow'] = df['yellow cards team1'] + df['yellow cards team2']

# ordenar pelos jogos com mais cartões
top10_cartoes = df.sort_values(by='total_yellow', ascending=False)

# selecionar colunas relevantes e pegar os 10 primeiros
resultado = top10_cartoes[['team1', 'team2','yellow cards team1','yellow cards team2','total_yellow']].head(10)

# exibir formatado
display(resultado)

,team1,team2,yellow cards team1,yellow cards team2,total_yellow
57,NETHERLANDS,ARGENTINA,8,8,16
46,SERBIA,SWITZERLAND,7,4,11
39,SAUDI ARABIA,MEXICO,6,1,7
44,GHANA,URUGUAY,2,5,7
47,CAMEROON,BRAZIL,5,2,7
63,ARGENTINA,FRANCE,4,3,7
0,QATAR,ECUADOR,4,2,6
3,UNITED STATES,WALES,4,2,6
24,JAPAN,COSTA RICA,3,3,6
17,QATAR,SENEGAL,3,3,6

In [18]:
# ==========================================================
# PERGUNTA 9:
# Quais os times sofreram mais FALTAS (cite os 10 primeiros)?
# ==========================================================
# soma total de faltas sofridas por cada time

def fouls_suffered(df):
    # Faltas sofridas quando o time é team1
    fouls_team1 = df.groupby('team1')['fouls against team1'].sum()
    # Faltas sofridas quando o time é team2
    fouls_team2 = df.groupby('team2')['fouls against team2'].sum()
    # Somar os dois
    total_fouls = fouls_team1.add(fouls_team2, fill_value=0)
    # Transformar em DataFrame limpo
    fouls_df = total_fouls.reset_index()
    fouls_df.columns = ['Time', 'Faltas sofridas']
    return fouls_df

fouls_suffered(df).sort_values('Faltas sofridas', ascending=False).head(10)

            Time  Faltas sofridas
0      ARGENTINA              100
18       MOROCCO               97
7        CROATIA               90
19   NETHERLANDS               87
11        FRANCE               69
3         BRAZIL               63
15         JAPAN               58
23  SAUDI ARABIA               56
21      PORTUGAL               56
10       ENGLAND               53

In [20]:
# ==========================================================
# PERGUNTA 10:
# Quais os times tiveram mais ESCANTEIOS (cite os 10 primeiros)?
# ==========================================================
def total_corners(df):
    # Escanteios quando o time é team1
    corners_team1 = df.groupby('team1')['corners team1'].sum()
    # Escanteios quando o time é team2
    corners_team2 = df.groupby('team2')['corners team2'].sum()
    # Somar os dois
    total_corners = corners_team1.add(corners_team2, fill_value=0)
    # Transformar em DataFrame limpo
    corners_df = total_corners.reset_index()
    corners_df.columns = ['Time', 'Total Escanteios']
    return corners_df

total_corners(df).sort_values('Total Escanteios', ascending=False).head(10)

              Time  Total Escanteios
0        ARGENTINA                39
11          FRANCE                38
3           BRAZIL                37
7          CROATIA                30
21        PORTUGAL                28
10         ENGLAND                25
12         GERMANY                25
16  KOREA REPUBLIC                24
24         SENEGAL                22
29   UNITED STATES                22

In [21]:
# ==========================================================
# PERGUNTA 11:
# Quais os times tiveram mais IMPEDIMENTOS (cite os 10 primeiros)?
# ==========================================================
# soma total de impedimentos por time

def total_offsides(df):
    # Impedimentos quando o time é team1
    offsides_team1 = df.groupby('team1')['offsides team1'].sum()
    # Impedimentos quando o time é team2
    offsides_team2 = df.groupby('team2')['offsides team2'].sum()
    # Somar os dois
    total_offsides = offsides_team1.add(offsides_team2, fill_value=0)
    # Transformar em DataFrame limpo
    offsides_df = total_offsides.reset_index()
    offsides_df.columns = ['Time', 'Total de Impedimentos']
    return offsides_df

total_offsides(df).sort_values('Total de Impedimentos', ascending=False).head(10)

          Time  Total de Impedimentos
0    ARGENTINA                     23
18     MOROCCO                     19
11      FRANCE                     16
6   COSTA RICA                     13
17      MEXICO                     13
21    PORTUGAL                     13
12     GERMANY                     12
7      CROATIA                     11
26       SPAIN                     11
15       JAPAN                      9

In [22]:
# ==========================================================
# PERGUNTA 12:
# Quais os times apresentaram maior PRESSÃO DEFENSIVA (cite os 10 primeiros)?
# ==========================================================

# soma total de pressões defensivas aplicadas por time

def total_defensive_pressure(df):
    # Pressão defensiva quando o time é team1
    pressure_team1 = df.groupby('team1')['defensive pressures applied team1'].sum()
    # Pressão defensiva quando o time é team2
    pressure_team2 = df.groupby('team2')['defensive pressures applied team2'].sum()
    # Somar os dois
    total_pressure = pressure_team1.add(pressure_team2, fill_value=0)
    # Transformar em DataFrame limpo
    pressure_df = total_pressure.reset_index()
    pressure_df.columns = ['Team', 'Total Defensive Pressure']
    return pressure_df

total_defensive_pressure(df).sort_values('Total Defensive Pressure', ascending=False).head(10)

           Team  Total Defensive Pressure
18      MOROCCO                      2516
7       CROATIA                      2113
11       FRANCE                      1986
15        JAPAN                      1829
0     ARGENTINA                      1688
19  NETHERLANDS                      1550
3        BRAZIL                      1477
1     AUSTRALIA                      1383
20       POLAND                      1354
21     PORTUGAL                      1267